Repository mne-tools/mne-bids, pull requests merged in 2021-11, with the labels that each got.

#900 Clean up some bits
  .circleci/config.yml
  mne_bids/tests/test_copyfiles.py
  mne_bids/tests/test_path.py
  mne_bids/tests/test_pick.py
  mne_bids/tests/test_read.py
  mne_bids/tests/test_tsv_handler.py
  mne_bids/tests/test_utils.py
  mne_bids/tests/test_write.py
Labels: code-health

#896 MRG: Replace tmpdir with tmp_path fixture
  doc/requirements.txt
  mne_bids/commands/tests/test_cli.py
  mne_bids/tests/test_copyfiles.py
  mne_bids/tests/test_path.py
  mne_bids/tests/test_read.py
  mne_bids/tests/test_report.py
  mne_bids/tests/test_stats.py
  mne_bids/tests/test_tsv_handler.py
  mne_bids/tests/test_update.py
  mne_bids/tests/test_write.py
Labels: code-health, tests

#908 MRG: get_entity_vals() gains new parameter ignore_dirs
  doc/whats_new.rst
  mne_bids/path.py
  mne_bids/tests/test_path.py
Labels: bug, API

#910 MRG: Various doc improvements
  doc/conf.py
  mne_bids/copyfiles.py
  mne_bids/dig.py
  mne_bids/inspect.py
  mne_bids/path.py
  mne_bids/read.py
  mne_bids/report.py
  mne_bids/sidecar_updates.py
  mne_bids/stats.py
  mne_bids/write.py
Labels: doc

#918 [MRG] CI/Maint: speed up circleci builds with machine executor
  .circleci/config.yml
  doc/authors.rst
Labels: maint
